apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ivn2
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0064-tenant/tkrw-pr712-0075-0064-app/devfile-sample-ivn2@sha256:bc608f9735d4b40edabc35decfa5d8bef4ba6ce9d14f985a6dbcfa34a89ed3ce
        name: my-nodejs
        resources: {}
status: {}
